{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "71839fb8-12dc-47f9-a4fa-49ae1f1cc59f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== Full Sweep: Asym wells, Phase Zoom, Variance, Hi-Res, Goldstone Test ===\n",
      "\n",
      "μ_I = 0.0\n",
      "Total density: 1.000000   Max density: 0.078223\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.0488/0.0492   sep = 13.0779 pm\n",
      "\n",
      "μ_I = 1.0\n",
      "Total density: 1.000000   Max density: 0.089426\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.0544/0.0550   sep = 11.8623 pm\n",
      "\n",
      "μ_I = 1.4\n",
      "Total density: 1.000000   Max density: 0.105525\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.0642/0.0653   sep = 10.3162 pm\n",
      "\n",
      "μ_I = 1.6\n",
      "Total density: 1.000000   Max density: 0.120430\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.0780/0.0808   sep = 8.8026 pm\n",
      "\n",
      "μ_I = 1.8\n",
      "Total density: 1.000000   Max density: 0.145980\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.1204/0.1269   sep = 6.7751 pm\n",
      "Single Gaussian fit: A = 0.0679, center = 0.0671, σ = 6.2649 pm\n",
      "Goldstone noise test: Fidelity after noise + 50 steps re-evolve: 0.9842\n",
      "\n",
      "μ_I = 2.0\n",
      "(Using higher res: N=2048, dx=0.05 pm)\n",
      "Total density: 0.500000   Max density: 0.140505\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.1318/0.1396   sep = 5.9900 pm\n",
      "Single Gaussian fit: A = 0.0488, center = 0.1745, σ = -4.4523 pm\n",
      "Goldstone noise test: Fidelity after noise + 50 steps re-evolve: 0.9999\n",
      "\n",
      "μ_I = 2.2\n",
      "(Using higher res: N=2048, dx=0.05 pm)\n",
      "Total density: 0.500000   Max density: 0.188864\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.1682/0.1894   sep = 5.8238 pm\n",
      "Single Gaussian fit: A = 0.0000, center = -0.0819, σ = -0.0372 pm\n",
      "\n",
      "μ_I = 3.0\n",
      "(Using higher res: N=2048, dx=0.05 pm)\n",
      "Total density: 0.500000   Max density: 1.216932\n",
      "Phase variance (high-density region): 0.0000 rad²\n",
      "Double fit: A1/A2 = 0.0000/0.4369   sep = 5.1868 pm\n",
      "Single Gaussian fit: A = 0.4369, center = 2.3334, σ = 0.4753 pm\n",
      "\n",
      "Sweep complete. Check PNGs (phase_zoom_*, density_*, noise_relax_*) and phase variance values.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from scipy.fftpack import fft, ifft\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "# ────────────────────────────────────────────────\n",
    "# Global / default parameters & fallback grid\n",
    "# ────────────────────────────────────────────────\n",
    "dt = 0.01\n",
    "g = 100.0\n",
    "mu = 10.0\n",
    "\n",
    "barrier_height = 20.0\n",
    "barrier_width = 1.0\n",
    "well_sep = 5.0\n",
    "\n",
    "# Default (normal) resolution grid & potential (fallback)\n",
    "N = 1024\n",
    "dx = 0.1\n",
    "x = dx * (np.arange(N) - N//2)\n",
    "k = 2 * np.pi * np.fft.fftfreq(N, d=dx)\n",
    "k2 = k**2 / 2\n",
    "\n",
    "V = barrier_height * np.exp(-x**2 / (2 * barrier_width**2))\n",
    "V -= 5.0 * np.exp(-(x - well_sep/2)**2 / 2)          # left\n",
    "V -= 4.8 * np.exp(-(x + well_sep/2)**2 / 2)          # right (bias)\n",
    "\n",
    "# ────────────────────────────────────────────────\n",
    "# Fit functions\n",
    "# ────────────────────────────────────────────────\n",
    "def double_gauss(x, A1, mu1, sigma1, A2, mu2, sigma2):\n",
    "    return A1 * np.exp(-(x-mu1)**2 / (2*sigma1**2)) + A2 * np.exp(-(x-mu2)**2 / (2*sigma2**2))\n",
    "\n",
    "def single_gauss(x, A, mu, sigma):\n",
    "    return A * np.exp(-(x-mu)**2 / (2*sigma**2))\n",
    "\n",
    "p0_double = [0.1, -2.5, 1.0, 0.1, 2.5, 1.0]\n",
    "p0_single = [0.2, 0.0, 2.0]\n",
    "\n",
    "# ────────────────────────────────────────────────\n",
    "# GPE imaginary-time step\n",
    "# ────────────────────────────────────────────────\n",
    "def gpe_imag_time_step(psi, V, g, dt, k2, mu_I=0.0):\n",
    "    V_eff = V - (mu_I**2 * 20.0) * np.abs(psi)**2\n",
    "    psi = np.exp(-dt / 2 * (V_eff + g * np.abs(psi)**2 - mu)) * psi\n",
    "    psi_k = fft(psi)\n",
    "    psi_k = np.exp(-dt * k2) * psi_k\n",
    "    psi = ifft(psi_k)\n",
    "    psi = np.exp(-dt / 2 * (V_eff + g * np.abs(psi)**2 - mu)) * psi\n",
    "    norm = np.sqrt(np.sum(np.abs(psi)**2) * dx)  # note: dx is global fallback\n",
    "    psi /= norm\n",
    "    return psi\n",
    "\n",
    "# ────────────────────────────────────────────────\n",
    "# Goldstone noise test (add small phase noise → re-evolve → fidelity)\n",
    "# ────────────────────────────────────────────────\n",
    "def goldstone_noise_test(psi, V, g, dt, k2, mu_I, noise_amp=0.1, steps=50):\n",
    "    phase_noise = noise_amp * np.random.randn(len(psi))\n",
    "    psi_noisy = psi * np.exp(1j * phase_noise)\n",
    "    \n",
    "    for _ in range(steps):\n",
    "        psi_noisy = gpe_imag_time_step(psi_noisy, V, g, dt, k2, mu_I)\n",
    "    \n",
    "    fidelity = np.abs(np.sum(np.conj(psi) * psi_noisy) * dx)**2\n",
    "    return psi_noisy, fidelity\n",
    "\n",
    "# ────────────────────────────────────────────────\n",
    "# Main sweep\n",
    "# ────────────────────────────────────────────────\n",
    "mu_I_values = [0.0, 1.0, 1.4, 1.6, 1.8, 2.0, 2.2, 3.0]\n",
    "print(\"\\n=== Full Sweep: Asym wells, Phase Zoom, Variance, Hi-Res, Goldstone Test ===\")\n",
    "\n",
    "for mu_I_val in mu_I_values:\n",
    "    print(f\"\\nμ_I = {mu_I_val:.1f}\")\n",
    "    \n",
    "    # Higher res for high μ_I (to resolve sharp spikes)\n",
    "    if mu_I_val >= 2.0:\n",
    "        N_local = 2048\n",
    "        dx_local = 0.05\n",
    "        x_local = dx_local * (np.arange(N_local) - N_local//2)\n",
    "        k_local = 2 * np.pi * np.fft.fftfreq(N_local, d=dx_local)\n",
    "        k2_local = k_local**2 / 2\n",
    "        \n",
    "        V_local = barrier_height * np.exp(-x_local**2 / (2 * barrier_width**2))\n",
    "        V_local -= 5.0 * np.exp(-(x_local - well_sep/2)**2 / 2)\n",
    "        V_local -= 4.8 * np.exp(-(x_local + well_sep/2)**2 / 2)\n",
    "        \n",
    "        print(f\"(Using higher res: N={N_local}, dx={dx_local} pm)\")\n",
    "    else:\n",
    "        N_local = N\n",
    "        dx_local = dx\n",
    "        x_local = x\n",
    "        V_local = V\n",
    "        k2_local = k2\n",
    "    \n",
    "    # Initial condition\n",
    "    psi = np.exp(-x_local**2 / 20) / np.pi**0.25\n",
    "    psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx_local)\n",
    "    \n",
    "    # More steps for high μ_I\n",
    "    steps = 200 if mu_I_val >= 2.0 else 120\n",
    "    for _ in range(steps):\n",
    "        psi = gpe_imag_time_step(psi, V_local, g, dt, k2_local, mu_I=mu_I_val)\n",
    "    \n",
    "    density = np.abs(psi)**2\n",
    "    total_n = np.trapezoid(density, x_local)\n",
    "    max_d = np.max(density)\n",
    "    print(f\"Total density: {total_n:.6f}   Max density: {max_d:.6f}\")\n",
    "    \n",
    "    # Phase & variance in high-density region (>10% max)\n",
    "    phase = np.unwrap(np.angle(psi))\n",
    "    high_dens_mask = density > 0.1 * max_d\n",
    "    phase_var = np.var(phase[high_dens_mask]) if np.any(high_dens_mask) else np.nan\n",
    "    print(f\"Phase variance (high-density region): {phase_var:.4f} rad²\")\n",
    "    \n",
    "    # Full phase plot\n",
    "    plt.figure(figsize=(8,4))\n",
    "    plt.plot(x_local, phase, 'g-')\n",
    "    plt.xlabel('x (pm)'); plt.ylabel('Phase (rad)')\n",
    "    plt.title(f'Phase at μ_I = {mu_I_val:.1f}')\n",
    "    plt.grid(True, alpha=0.3)\n",
    "    plt.savefig(f'phase_muI_{mu_I_val:.1f}.png', dpi=150, bbox_inches='tight')\n",
    "    plt.close()\n",
    "    \n",
    "    # Zoom phase (|x| < 10 pm)\n",
    "    zoom_mask = np.abs(x_local) < 10\n",
    "    if np.any(zoom_mask):\n",
    "        plt.figure(figsize=(6,4))\n",
    "        plt.plot(x_local[zoom_mask], phase[zoom_mask], 'g-')\n",
    "        plt.xlabel('x (pm)'); plt.ylabel('Phase (rad)')\n",
    "        plt.title(f'Phase zoom (|x|<10 pm) at μ_I = {mu_I_val:.1f}')\n",
    "        plt.grid(True, alpha=0.3)\n",
    "        plt.savefig(f'phase_zoom_muI_{mu_I_val:.1f}.png', dpi=200, bbox_inches='tight')\n",
    "        plt.close()\n",
    "    \n",
    "    # Density fits\n",
    "    fit_success = False\n",
    "    try:\n",
    "        popt_d, _ = curve_fit(double_gauss, x_local, density, p0=p0_double, maxfev=8000)\n",
    "        sep = abs(popt_d[1] - popt_d[4])\n",
    "        print(f\"Double fit: A1/A2 = {popt_d[0]:.4f}/{popt_d[3]:.4f}   sep = {sep:.4f} pm\")\n",
    "        fit_success = True\n",
    "    except:\n",
    "        print(\"Double Gaussian fit failed\")\n",
    "    \n",
    "    if not fit_success or sep < 7.0:\n",
    "        try:\n",
    "            popt_s, _ = curve_fit(single_gauss, x_local, density, p0=p0_single, maxfev=5000)\n",
    "            print(f\"Single Gaussian fit: A = {popt_s[0]:.4f}, center = {popt_s[1]:.4f}, σ = {popt_s[2]:.4f} pm\")\n",
    "        except:\n",
    "            print(\"Single Gaussian fit failed\")\n",
    "    \n",
    "    # Density plot\n",
    "    plt.figure(figsize=(8,5))\n",
    "    plt.plot(x_local, density, 'b-', label='Density')\n",
    "    try:\n",
    "        plt.plot(x_local, double_gauss(x_local, *popt_d), 'r--', label='Double fit')\n",
    "    except:\n",
    "        pass\n",
    "    try:\n",
    "        plt.plot(x_local, single_gauss(x_local, *popt_s), 'm--', label='Single fit')\n",
    "    except:\n",
    "        pass\n",
    "    plt.xlabel('x (pm)'); plt.ylabel('|ψ|²')\n",
    "    plt.title(f'Density at μ_I = {mu_I_val:.1f} (asym wells)')\n",
    "    plt.legend(); plt.grid(True, alpha=0.3)\n",
    "    plt.savefig(f'density_muI_{mu_I_val:.1f}.png', dpi=150, bbox_inches='tight')\n",
    "    plt.close()\n",
    "    \n",
    "    # Goldstone noise test at transition points\n",
    "    if mu_I_val in [1.8, 2.0]:\n",
    "        psi_noisy, fidelity = goldstone_noise_test(psi, V_local, g, dt, k2_local, mu_I_val, noise_amp=0.1, steps=50)\n",
    "        print(f\"Goldstone noise test: Fidelity after noise + 50 steps re-evolve: {fidelity:.4f}\")\n",
    "        # Save noisy relaxed density\n",
    "        plt.figure(figsize=(8,5))\n",
    "        plt.plot(x_local, np.abs(psi_noisy)**2, 'c-', label='After noise + relaxation')\n",
    "        plt.xlabel('x (pm)'); plt.ylabel('|ψ|²')\n",
    "        plt.title(f'Noisy density after relaxation at μ_I = {mu_I_val:.1f}')\n",
    "        plt.legend(); plt.grid(True, alpha=0.3)\n",
    "        plt.savefig(f'noise_relax_muI_{mu_I_val:.1f}.png', dpi=150, bbox_inches='tight')\n",
    "        plt.close()\n",
    "\n",
    "print(\"\\nSweep complete. Check PNGs (phase_zoom_*, density_*, noise_relax_*) and phase variance values.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0dd0ef54-c33c-46bd-b6e7-2b8c17dd307d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
