{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5ee77095-98a6-41ab-be2e-4034cebe190d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== μ_I Sweep (coefficient *20.0) ===\n",
      "\n",
      "μ_I = 0.0\n",
      "Total integrated density: 1.000000\n",
      "Max density: 0.078099\n",
      "A1 / A2: 0.0490 / 0.0490\n",
      "mu1 / mu2: -6.5056 / 6.5056\n",
      "Centers separation: 13.0112 pm\n",
      "Average lobe width (sigma): 4.1372 pm\n",
      "\n",
      "μ_I = 0.5\n",
      "Total integrated density: 1.000000\n",
      "Max density: 0.080526\n",
      "A1 / A2: 0.0502 / 0.0502\n",
      "mu1 / mu2: -6.3647 / 6.3647\n",
      "Centers separation: 12.7293 pm\n",
      "Average lobe width (sigma): 4.0314 pm\n",
      "\n",
      "μ_I = 1.0\n",
      "Total integrated density: 1.000000\n",
      "Max density: 0.089259\n",
      "A1 / A2: 0.0547 / 0.0547\n",
      "mu1 / mu2: -5.8929 / 5.8929\n",
      "Centers separation: 11.7859 pm\n",
      "Average lobe width (sigma): 3.6639 pm\n",
      "\n",
      "μ_I = 1.5\n",
      "Total integrated density: 1.000000\n",
      "Max density: 0.111816\n",
      "A1 / A2: 0.0709 / 0.0709\n",
      "mu1 / mu2: -4.7821 / 4.7819\n",
      "Centers separation: 9.5640 pm\n",
      "Average lobe width (sigma): 2.7055 pm\n",
      "\n",
      "μ_I = 2.0\n",
      "Total integrated density: 1.000000\n",
      "Max density: 0.196160\n",
      "A1 / A2: 0.1867 / 0.1867\n",
      "mu1 / mu2: -3.1213 / 3.1213\n",
      "Centers separation: 6.2425 pm\n",
      "Average lobe width (sigma): 0.9341 pm\n",
      "\n",
      "μ_I = 3.0\n",
      "Total integrated density: 1.000000\n",
      "Max density: 2.548518\n",
      "A1 / A2: 2.5510 / 1.1908\n",
      "mu1 / mu2: -2.6021 / 2.1573\n",
      "Centers separation: 4.7595 pm\n",
      "Average lobe width (sigma): 0.0894 pm\n",
      "\n",
      "Sweep complete. Check the saved PNG files for visual comparison.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from scipy.fftpack import fft, ifft\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "# Parameters in pm units (1 Å = 100 pm)\n",
    "N = 1024  # grid points\n",
    "dx = 0.1  # pm\n",
    "x = dx * (np.arange(N) - N//2)  # centered grid, range ~ -50 to 50 pm\n",
    "dt = 0.01  # time step (arbitrary units)\n",
    "g = 100.0  # interaction strength\n",
    "mu = 10.0  # chemical potential guess for norm\n",
    "\n",
    "# Double-well potential: two Gaussians separated by barrier\n",
    "barrier_height = 20.0\n",
    "barrier_width = 1.0  # pm\n",
    "well_sep = 5.0  # pm\n",
    "V = barrier_height * np.exp(-x**2 / (2 * barrier_width**2))  # central barrier\n",
    "V -= 5.0 * (np.exp(-(x - well_sep/2)**2 / 2) + np.exp(-(x + well_sep/2)**2 / 2))  # two wells\n",
    "\n",
    "# Kinetic operator in k-space\n",
    "k = 2 * np.pi * np.fft.fftfreq(N, d=dx)\n",
    "k2 = k**2 / 2\n",
    "\n",
    "def gpe_imag_time_step(psi, V, g, dt, k2, mu_I=0.0):\n",
    "    # Effective potential with pion condensation term\n",
    "    V_eff = V - (mu_I**2 * 20.0) * np.abs(psi)**2   # *20.0 for noticeable effect\n",
    "    # Nonlinear + potential half-step\n",
    "    psi = np.exp(-dt / 2 * (V_eff + g * np.abs(psi)**2 - mu)) * psi\n",
    "    # Fourier kinetic\n",
    "    psi_k = fft(psi)\n",
    "    psi_k = np.exp(-dt * k2) * psi_k\n",
    "    psi = ifft(psi_k)\n",
    "    # Second half-step\n",
    "    psi = np.exp(-dt / 2 * (V_eff + g * np.abs(psi)**2 - mu)) * psi\n",
    "    # Normalize\n",
    "    norm = np.sqrt(np.sum(np.abs(psi)**2) * dx)\n",
    "    psi /= norm\n",
    "    return psi\n",
    "\n",
    "# Fit function\n",
    "def double_gauss(x, A1, mu1, sigma1, A2, mu2, sigma2):\n",
    "    return A1 * np.exp(-(x-mu1)**2 / (2*sigma1**2)) + A2 * np.exp(-(x-mu2)**2 / (2*sigma2**2))\n",
    "\n",
    "p0 = [0.1, -2.5, 1.0, 0.1, 2.5, 1.0]  # initial guess\n",
    "\n",
    "# μ_I Sweep with progression table\n",
    "mu_I_values = [0.0, 0.5, 1.0, 1.5, 2.0, 3.0]\n",
    "print(\"\\n=== μ_I Sweep (coefficient *20.0) ===\")\n",
    "\n",
    "for mu_I_val in mu_I_values:\n",
    "    print(f\"\\nμ_I = {mu_I_val:.1f}\")\n",
    "    \n",
    "    # Fresh initial condition each time\n",
    "    psi = np.exp(-x**2 / 20) / np.pi**0.25\n",
    "    psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx)\n",
    "    \n",
    "    # Evolve (120 steps for better convergence at higher μ_I)\n",
    "    for _ in range(120):\n",
    "        psi = gpe_imag_time_step(psi, V, g, dt, k2, mu_I=mu_I_val)\n",
    "    \n",
    "    density = np.abs(psi)**2\n",
    "    total_n = np.trapezoid(density, x)\n",
    "    max_d = np.max(density)\n",
    "    \n",
    "    print(f\"Total integrated density: {total_n:.6f}\")\n",
    "    print(f\"Max density: {max_d:.6f}\")\n",
    "    \n",
    "    try:\n",
    "        popt, _ = curve_fit(double_gauss, x, density, p0=p0, maxfev=5000)\n",
    "        sep = abs(popt[1] - popt[4])\n",
    "        avg_sigma = (popt[2] + popt[5]) / 2\n",
    "        print(f\"A1 / A2: {popt[0]:.4f} / {popt[3]:.4f}\")\n",
    "        print(f\"mu1 / mu2: {popt[1]:.4f} / {popt[4]:.4f}\")\n",
    "        print(f\"Centers separation: {sep:.4f} pm\")\n",
    "        print(f\"Average lobe width (sigma): {avg_sigma:.4f} pm\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fit failed: {str(e)}\")\n",
    "    \n",
    "    # Optional: save density plot for this μ_I\n",
    "    plt.figure(figsize=(8,5))\n",
    "    plt.plot(x, density, 'b-', label='Density')\n",
    "    try:\n",
    "        plt.plot(x, double_gauss(x, *popt), 'r--', label='Fit')\n",
    "    except:\n",
    "        pass\n",
    "    plt.xlabel('x (pm)')\n",
    "    plt.ylabel('|ψ|²')\n",
    "    plt.title(f'Density at μ_I = {mu_I_val:.1f}')\n",
    "    plt.legend()\n",
    "    plt.grid(True, alpha=0.3)\n",
    "    plt.savefig(f'density_muI_{mu_I_val:.1f}.png', dpi=150, bbox_inches='tight')\n",
    "    plt.close()\n",
    "\n",
    "print(\"\\nSweep complete. Check the saved PNG files for visual comparison.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6cee3d7-cd55-4d25-801f-6dd583ca0e8e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
