{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cf23106b-900d-4f12-8239-918ed9a1397a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Double Gaussian fit (pm units):\n",
      "A1 = 0.0537, mu1 = -6.1356, sigma1 = 3.7640\n",
      "A2 = 0.0537, mu2 = 6.1356, sigma2 = 3.7640\n",
      "Total integrated density (should be ~1): 0.9999999999999999\n",
      "Max density: 0.08111173423171629\n",
      "Centers separation from fit: 12.27124676478657\n",
      "Average lobe width (sigma): 3.763991073789075\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from scipy.fftpack import fft, ifft\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.optimize import curve_fit\n",
    "# Parameters in pm units (1 Å = 100 pm)\n",
    "N = 1024  # grid points\n",
    "dx = 0.1  # pm\n",
    "x = dx * (np.arange(N) - N//2)  # centered grid, range ~ -50 to 50 pm\n",
    "dt = 0.01  # time step (arbitrary units)\n",
    "g = 100.0  # interaction strength (tune for ξ ~ 1 / sqrt(g |ψ|^2) ~ pm)\n",
    "mu = 10.0  # chemical potential guess for norm\n",
    "\n",
    "# Double-well potential: two Gaussians separated by barrier\n",
    "barrier_height = 20.0\n",
    "barrier_width = 1.0  # pm\n",
    "well_sep = 5.0  # pm\n",
    "V = barrier_height * np.exp(-x**2 / (2 * barrier_width**2))  # central barrier\n",
    "V -= 5.0 * (np.exp(-(x - well_sep/2)**2 / 2) + np.exp(-(x + well_sep/2)**2 / 2))  # two wells\n",
    "\n",
    "# Kinetic operator in k-space\n",
    "k = 2 * np.pi * np.fft.fftfreq(N, d=dx)\n",
    "k2 = k**2 / 2\n",
    "\n",
    "def gpe_imag_time_step(psi, V, g, dt, k2):\n",
    "    # Nonlinear + potential half-step\n",
    "    psi = np.exp(-dt / 2 * (V + g * np.abs(psi)**2 - mu)) * psi\n",
    "    # Fourier kinetic\n",
    "    psi_k = fft(psi)\n",
    "    psi_k = np.exp(-dt * k2) * psi_k\n",
    "    psi = ifft(psi_k)\n",
    "    # Second half-step\n",
    "    psi = np.exp(-dt / 2 * (V + g * np.abs(psi)**2 - mu)) * psi\n",
    "    # Normalize\n",
    "    norm = np.sqrt(np.sum(np.abs(psi)**2) * dx)\n",
    "    psi /= norm\n",
    "    return psi\n",
    "\n",
    "# Initial psi: broad Gaussian\n",
    "psi = np.exp(-x**2 / 20) / np.pi**0.25\n",
    "psi /= np.sqrt(np.sum(np.abs(psi)**2) * dx)  # norm 1\n",
    "\n",
    "# Imaginary time evolution for ground state (100 steps for convergence)\n",
    "for _ in range(100):\n",
    "    psi = gpe_imag_time_step(psi, V, g, dt, k2)\n",
    "\n",
    "# Density |psi|^2 should show double Gaussian\n",
    "density = np.abs(psi)**2\n",
    "\n",
    "# Fit double Gaussian\n",
    "def double_gauss(x, A1, mu1, sigma1, A2, mu2, sigma2):\n",
    "    return A1 * np.exp(-(x-mu1)**2 / (2*sigma1**2)) + A2 * np.exp(-(x-mu2)**2 / (2*sigma2**2))\n",
    "\n",
    "p0 = [0.1, -2.5, 1.0, 0.1, 2.5, 1.0]  # guesses for amplitudes, centers, sigmas\n",
    "popt, pcov = curve_fit(double_gauss, x, density, p0=p0)\n",
    "print(\"Double Gaussian fit (pm units):\")\n",
    "print(f\"A1 = {popt[0]:.4f}, mu1 = {popt[1]:.4f}, sigma1 = {popt[2]:.4f}\")\n",
    "print(f\"A2 = {popt[3]:.4f}, mu2 = {popt[4]:.4f}, sigma2 = {popt[5]:.4f}\")\n",
    "print(\"Total integrated density (should be ~1):\", np.trapezoid(density, x))\n",
    "print(\"Max density:\", np.max(density))\n",
    "print(\"Centers separation from fit:\", abs(popt[1] - popt[4]))\n",
    "print(\"Average lobe width (sigma):\", (popt[2] + popt[5])/2)\n",
    "\n",
    "# Plot density + fit\n",
    "plt.plot(x, density, 'b-', label='Density')\n",
    "plt.plot(x, double_gauss(x, *popt), 'r--', label='Fit')\n",
    "plt.xlabel('x (pm)')\n",
    "plt.ylabel('|psi|^2')\n",
    "plt.title('BEC Double Gaussian Density')\n",
    "plt.legend()\n",
    "plt.savefig('bec_density_fit.png', dpi=150, bbox_inches='tight')\n",
    "plt.close()  # free memory\n",
    "\n",
    "# Phase plot\n",
    "phase = np.unwrap(np.angle(psi))\n",
    "plt.plot(x, phase, 'g-', label='Phase')\n",
    "plt.xlabel('x (pm)')\n",
    "plt.ylabel('Phase (rad)')\n",
    "plt.title('BEC Phase Profile')\n",
    "plt.legend()\n",
    "plt.savefig('bec_phase_profile.png', dpi=150, bbox_inches='tight')\n",
    "plt.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c18bea9c-a70a-4b81-bcc1-daeacb4fd4f6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
